// This file was generated by counterfeiter
package notificationsfakes

import (
	"cred-alert/notifications"
	"sync"
)

type FakeNotifier struct {
	SendNotificationStub        func(message string) error
	sendNotificationMutex       sync.RWMutex
	sendNotificationArgsForCall []struct {
		message string
	}
	sendNotificationReturns struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeNotifier) SendNotification(message string) error {
	fake.sendNotificationMutex.Lock()
	fake.sendNotificationArgsForCall = append(fake.sendNotificationArgsForCall, struct {
		message string
	}{message})
	fake.recordInvocation("SendNotification", []interface{}{message})
	fake.sendNotificationMutex.Unlock()
	if fake.SendNotificationStub != nil {
		return fake.SendNotificationStub(message)
	} else {
		return fake.sendNotificationReturns.result1
	}
}

func (fake *FakeNotifier) SendNotificationCallCount() int {
	fake.sendNotificationMutex.RLock()
	defer fake.sendNotificationMutex.RUnlock()
	return len(fake.sendNotificationArgsForCall)
}

func (fake *FakeNotifier) SendNotificationArgsForCall(i int) string {
	fake.sendNotificationMutex.RLock()
	defer fake.sendNotificationMutex.RUnlock()
	return fake.sendNotificationArgsForCall[i].message
}

func (fake *FakeNotifier) SendNotificationReturns(result1 error) {
	fake.SendNotificationStub = nil
	fake.sendNotificationReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeNotifier) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.sendNotificationMutex.RLock()
	defer fake.sendNotificationMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeNotifier) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ notifications.Notifier = new(FakeNotifier)
