// This file was generated by counterfeiter
package queuefakes

import (
	"cred-alert/queue"
	"sync"

	"cloud.google.com/go/pubsub"
	"golang.org/x/net/context"
)

type FakeTopic struct {
	PublishStub        func(context.Context, *pubsub.Message) *pubsub.PublishResult
	publishMutex       sync.RWMutex
	publishArgsForCall []struct {
		arg1 context.Context
		arg2 *pubsub.Message
	}
	publishReturns struct {
		result1 *pubsub.PublishResult
	}
	publishReturnsOnCall map[int]struct {
		result1 *pubsub.PublishResult
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeTopic) Publish(arg1 context.Context, arg2 *pubsub.Message) *pubsub.PublishResult {
	fake.publishMutex.Lock()
	ret, specificReturn := fake.publishReturnsOnCall[len(fake.publishArgsForCall)]
	fake.publishArgsForCall = append(fake.publishArgsForCall, struct {
		arg1 context.Context
		arg2 *pubsub.Message
	}{arg1, arg2})
	fake.recordInvocation("Publish", []interface{}{arg1, arg2})
	fake.publishMutex.Unlock()
	if fake.PublishStub != nil {
		return fake.PublishStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.publishReturns.result1
}

func (fake *FakeTopic) PublishCallCount() int {
	fake.publishMutex.RLock()
	defer fake.publishMutex.RUnlock()
	return len(fake.publishArgsForCall)
}

func (fake *FakeTopic) PublishArgsForCall(i int) (context.Context, *pubsub.Message) {
	fake.publishMutex.RLock()
	defer fake.publishMutex.RUnlock()
	return fake.publishArgsForCall[i].arg1, fake.publishArgsForCall[i].arg2
}

func (fake *FakeTopic) PublishReturns(result1 *pubsub.PublishResult) {
	fake.PublishStub = nil
	fake.publishReturns = struct {
		result1 *pubsub.PublishResult
	}{result1}
}

func (fake *FakeTopic) PublishReturnsOnCall(i int, result1 *pubsub.PublishResult) {
	fake.PublishStub = nil
	if fake.publishReturnsOnCall == nil {
		fake.publishReturnsOnCall = make(map[int]struct {
			result1 *pubsub.PublishResult
		})
	}
	fake.publishReturnsOnCall[i] = struct {
		result1 *pubsub.PublishResult
	}{result1}
}

func (fake *FakeTopic) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.publishMutex.RLock()
	defer fake.publishMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeTopic) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ queue.Topic = new(FakeTopic)
