// This file was generated by counterfeiter
package matchersfakes

import (
	"cred-alert/sniff/matchers"
	"sync"
)

type FakeMatcher struct {
	MatchStub        func([]byte) bool
	matchMutex       sync.RWMutex
	matchArgsForCall []struct {
		arg1 []byte
	}
	matchReturns struct {
		result1 bool
	}
}

func (fake *FakeMatcher) Match(arg1 []byte) bool {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.matchMutex.Lock()
	fake.matchArgsForCall = append(fake.matchArgsForCall, struct {
		arg1 []byte
	}{arg1Copy})
	fake.matchMutex.Unlock()
	if fake.MatchStub != nil {
		return fake.MatchStub(arg1)
	} else {
		return fake.matchReturns.result1
	}
}

func (fake *FakeMatcher) MatchCallCount() int {
	fake.matchMutex.RLock()
	defer fake.matchMutex.RUnlock()
	return len(fake.matchArgsForCall)
}

func (fake *FakeMatcher) MatchArgsForCall(i int) []byte {
	fake.matchMutex.RLock()
	defer fake.matchMutex.RUnlock()
	return fake.matchArgsForCall[i].arg1
}

func (fake *FakeMatcher) MatchReturns(result1 bool) {
	fake.MatchStub = nil
	fake.matchReturns = struct {
		result1 bool
	}{result1}
}

var _ matchers.Matcher = new(FakeMatcher)
