// This file was generated by counterfeiter
package matchersfakes

import (
	"cred-alert/sniff/matchers"
	"sync"
)

type FakeMatcher struct {
	MatchStub        func([]byte) bool
	matchMutex       sync.RWMutex
	matchArgsForCall []struct {
		arg1 []byte
	}
	matchReturns struct {
		result1 bool
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMatcher) Match(arg1 []byte) bool {
	var arg1Copy []byte
	if arg1 != nil {
		arg1Copy = make([]byte, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.matchMutex.Lock()
	fake.matchArgsForCall = append(fake.matchArgsForCall, struct {
		arg1 []byte
	}{arg1Copy})
	fake.recordInvocation("Match", []interface{}{arg1Copy})
	fake.matchMutex.Unlock()
	if fake.MatchStub != nil {
		return fake.MatchStub(arg1)
	} else {
		return fake.matchReturns.result1
	}
}

func (fake *FakeMatcher) MatchCallCount() int {
	fake.matchMutex.RLock()
	defer fake.matchMutex.RUnlock()
	return len(fake.matchArgsForCall)
}

func (fake *FakeMatcher) MatchArgsForCall(i int) []byte {
	fake.matchMutex.RLock()
	defer fake.matchMutex.RUnlock()
	return fake.matchArgsForCall[i].arg1
}

func (fake *FakeMatcher) MatchReturns(result1 bool) {
	fake.MatchStub = nil
	fake.matchReturns = struct {
		result1 bool
	}{result1}
}

func (fake *FakeMatcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.matchMutex.RLock()
	defer fake.matchMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeMatcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ matchers.Matcher = new(FakeMatcher)
