#!/usr/bin/env bash

set -x -e

export GOPATH=$PWD/cred-alert
export PATH=$GOPATH/bin:$PATH

OUTPUT_DIR=$PWD/cred-alert-binary

GOARCH=amd64 GOOS=linux go build -o $OUTPUT_DIR/cred-alert cred-alert/cmd/cred-alert
