#!/usr/bin/env bash

set -e -u

export GOPATH=${PWD}/cred-alert
export PATH=${GOPATH}/bin:${PATH}

APP_DIR=${PWD}/cred-alert-app

echo "Building ingestor for environment '${ENVIRONMENT}'..."
GOARCH=amd64 GOOS=linux go build -o "${APP_DIR}/cred-alert-ingestor" cred-alert/cmd/cred-alert-ingestor
echo "Building worker for environment '${ENVIRONMENT}'..."
GOARCH=amd64 GOOS=linux go build -o "${APP_DIR}/cred-alert-worker" cred-alert/cmd/cred-alert-worker
