#!/usr/bin/env bash

set -e

OUTPUT="$PWD/bump-submodules-output"

pushd cred-alert
  git submodule update --remote --merge
popd

cred-alert/ci/scripts/test

pushd cred-alert
  git config --global user.name "Submodule Bumper"
  git config --global user.email "pcf-security-enablement+submodule-bumper@pivotal.io"

  git add .

  STATUS=$(git status --porcelain)

  if [ "$STATUS" != "" ]; then
    git commit -m "Update submodules"

    cat > "$OUTPUT/message" << EOF
Submodules were updated:

$STATUS
EOF
  fi
popd
