#!/usr/bin/env bash

set -eu

MESSAGE_PATH="$PWD/bump-submodules-message/message"
IN_REPO_PATH="$PWD/repo"
OUT_REPO_PATH="$PWD/bumped-repo"

git clone "$IN_REPO_PATH" "$OUT_REPO_PATH"

cd "$OUT_REPO_PATH"

git submodule update --init --remote

git add .

STATUS=$(git status --porcelain)

if [ "$STATUS" == "" ]; then
  exit 0
fi

git config --global user.name "Submodule Bumper"
git config --global user.email "pcf-security-enablement+submodule-bumper@pivotal.io"

git commit -m "Update submodules"

cat > "$MESSAGE_PATH" << EOF
Submodules were updated:

$STATUS
EOF
