#!/usr/bin/env bash

set -e -u

OUTPUT="${PWD}/cred-alert-cli-bundle"

for os in linux darwin; do
  pushd "${PWD}/cred-alert-${os}-cli"
    tar czvf "${OUTPUT}/cred-alert-cli_${os}.tgz" cred-alert-*
  popd
done
