#!/usr/bin/env bash

set -e -u

export GOPATH="${PWD}/cred-alert"
export PATH="${GOPATH}/bin:${PATH}"

OUTPUT="${PWD}/cred-alert-components"

GOARCH=amd64 GOOS=linux go build -x -v -o "${OUTPUT}/stats-monitor" cred-alert/cmd/stats-monitor
