#!/usr/bin/env bash

set -e -u

export GOPATH="${PWD}/cred-alert"
export PATH="${GOPATH}/bin:${PATH}"

OUTPUT="${PWD}/credential-count-binary"

go build -x -v -o "${OUTPUT}/credential-count-publisher" "cred-alert/cmd/credential-count-publisher"
