#!/usr/bin/env bash

set -e -u

export GOPATH="${PWD}/cred-alert"
export PATH="${GOPATH}/bin:${PATH}"

OUTPUT="${PWD}/cred-alert-components"

for component in cred-alert-ingestor cred-alert-worker stats-monitor; do
  echo "Building ${component}..."
  GOARCH=amd64 GOOS=linux go build -v -o "${OUTPUT}/${component}" "cred-alert/cmd/${component}"
done

