#!/usr/bin/env bash

set -e -u

export GOPATH="${PWD}/cred-alert"
export PATH="${GOPATH}/bin:${PATH}"

version=$(git --git-dir=${GOPATH}/.git rev-parse --short HEAD)

OUTPUT="${PWD}/cred-alert-cli-${GOOS}"

go build -ldflags "-X cred-alert/commands.version=${version}" -x -v -o "${OUTPUT}/cred-alert-cli_${GOOS}" "cred-alert/cmd/cred-alert-cli"
