#!/usr/bin/env bash

set -e

OUTPUT="$PWD/bosh-rc"
VERSION="$(cat version/version)"

pushd cred-alert/
  # work-around Go BOSH CLI trying to rename blobs downloaded into ~/.root/tmp
  # into release dir, which is invalid cross-device link
  export HOME=$PWD

  bosh -n create-release --tarball --name revok --version "$VERSION"
  mv releases/revok/revok-*.tgz "$OUTPUT"
popd
