#!/usr/bin/env bash
set -eu -o pipefail

export GOPATH="${PWD}/go"
export PATH="${GOPATH}/bin:${PATH}"

cred_alert_root=$(cd "$(dirname "${BASH_SOURCE}")"; cd ../..; pwd)

# set tag name
date +%Y-%m-%d-%H-%M-%S > release-params/tag-name

# set tag commit
pushd cred-alert
  git rev-parse HEAD > ../release-params/commit-sha
popd
