#!/usr/bin/env bash

set -e

RELEASE_TGZ="${PWD}/bosh-rc/revok-${VERSION}.tgz"
VERSION="$(cat version/version)"

pushd cred-alert/
  # work-around Go BOSH CLI trying to rename blobs downloaded into ~/.root/tmp
  # into release dir, which is invalid cross-device link
  export HOME=$PWD

  bosh -n create-release \
    --name revok \
    --version "$VERSION" \
    --tarball $RELEASE_TGZ
popd
