#!/usr/bin/env bash

set -e -u

export GOPATH="${PWD}/cred-alert"
export PATH="${GOPATH}/bin:${PATH}"

go build -x -v -o $WORKDIR/bin "cred-alert/cmd/credential-count-publisher"

mkdir -p $WORKDIR/{bin,certs,log}

cat > $WORKDIR/certs/ca.crt << EOF
$CA_CERT
EOF

cat > $WORKDIR/certs/client.crt << EOF
$CLIENT_CERT
EOF

cat > $WORKDIR/certs/client.key << EOF
$CLIENT_KEY
EOF

chmod 0400 $WORKDIR/certs/*

PLIST_PATH=~/Library/LaunchAgents/$LABEL.plist

cat > $PLIST_PATH << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>KeepAlive</key>
  <true/>
  <key>Label</key>
  <string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>$WORKDIR/bin/credential_count_publisher</string>
    <string>--rpc-server-address</string>
    <string>$RPC_SERVER_ADDRESS</string>
    <string>--rpc-server-port</string>
    <string>$RPC_SERVER_PORT</string>
    <string>--ca-cert-path</string>
    <string>certs/ca.crt</string>
    <string>--client-cert-path</string>
    <string>certs/client.crt</string>
    <string>--client-key-path</string>
    <string>certs/client.key</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>WorkingDirectory</key>
  <string>$WORKDIR</string>
  <key>StandardOutPath</key>
  <string>$WORKDIR/log/stdout.log</string>
  <key>StandardErrorPath</key>
  <string>$WORKDIR/log/stderr.log</string>
</dict>
</plist>
EOF

launchctl unload $PLIST_PATH
launchctl load $PLIST_PATH
