#!/bin/bash

set -e -x -u

curl -f -X POST -H "Content-type: application/json" -d "{                 \
    \"title\": \"Deployed cred-alert to ${ENVIRONMENT}\",                 \
    \"text\": \"Deployed cred-alert to ${ENVIRONMENT}\",                  \
    \"priority\": \"normal\",                                             \
    \"tags\": [\"deployment:${ENVIRONMENT}\"],                            \
    \"alert_type\": \"info\"                                              \
  }" "https://app.datadoghq.com/api/v1/events?api_key=${DATADOG_API_KEY}"
