#!/bin/bash

set -e -x

# inputs
CANDIDATE_DIR=$PWD/bosh-rc
BOSH_RELEASE_DIR=$PWD/bosh-release

# outputs
FINAL_RELEASE_TARBALL=$PWD/final-release-tarball
FINAL_RELEASE_REPO=$PWD/final-release-repo

VERSION=$(cat ./version/version)
if [ -z "$VERSION" ]; then
  echo "Version number not found in ./version/version"
  exit 1
fi

git clone $BOSH_RELEASE_DIR $FINAL_RELEASE_REPO

cp $BLOBSTORE_PRIVATE_YML_PATH $FINAL_RELEASE_REPO/config/private.yml

cd $FINAL_RELEASE_REPO

RELEASE_YML=$PWD/releases/$RELEASE_NAME/$RELEASE_NAME-${VERSION}.yml
RELEASE_TGZ=$PWD/releases/$RELEASE_NAME/$RELEASE_NAME-${VERSION}.tgz

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

# work-around Go BOSH CLI trying to rename blobs downloaded into ~/.root/tmp
# into release dir, which is invalid cross-device link
export HOME=$PWD

# be idempotent
if ! [ -e ${RELEASE_YML} ]; then
  echo "finalizing release"
  bosh -n finalize-release --version "$VERSION" ${CANDIDATE_DIR}/$RELEASE_NAME-*.tgz
  git add -A
  git commit -m "release v${VERSION}"
fi

bosh -n create-release --tarball ${RELEASE_YML}

mv ${RELEASE_TGZ} ${FINAL_RELEASE_TARBALL}
