#!/usr/bin/env bash

set -e

cat > credentials.yml <<EOF
revok-github-access-token: $GITHUB_ACCESS_TOKEN
github-webhook-secrets: ${GITHUB_WEBHOOK_SECRETS//\'/}

revok-mysql-username: $MYSQL_USERNAME
revok-mysql-password: $MYSQL_PASSWORD
revok-mysql-hostname: $MYSQL_HOSTNAME

revok-datadog-api-key: $DATADOG_API_KEY
revok-sentry-dsn: $SENTRY_DSN

revok-papertrail-address: $PAPERTRAIL_ADDRESS
revok-slack-webhook-url: $SLACK_WEBHOOK_URL
revok-ignore-repos: $IGNORE_REPOS

revok-rpc-server-bind-ip: $RPC_SERVER_BIND_IP
revok-rpc-server-bind-port: $RPC_SERVER_BIND_PORT
EOF

IFS=$'\n'
echo "revok-github-private-key: |" >> credentials.yml
for line in $GITHUB_PRIVATE_KEY; do
  echo "  $line" >> credentials.yml
done

echo "revok-github-public-key: |" >> credentials.yml
for line in $GITHUB_PUBLIC_KEY; do
  echo "  $line" >> credentials.yml
done

echo "revok-rpc-server-client-ca: |" >> credentials.yml
for line in $RPC_SERVER_CLIENT_CA; do
  echo "  $line" >> credentials.yml
done

echo "revok-rpc-server-cert: |" >> credentials.yml
for line in $RPC_SERVER_CERT; do
  echo "  $line" >> credentials.yml
done

echo "revok-rpc-server-private-key: |" >> credentials.yml
for line in $RPC_SERVER_PRIVATE_KEY; do
  echo "  $line" >> credentials.yml
done

echo "revok-pubsub-public-key: |" >> credentials.yml
for line in $PUBSUB_PUBLIC_KEY; do
  echo "  $line" >> credentials.yml
done

echo "revok-pubsub-private-key: |" >> credentials.yml
for line in $PUBSUB_PRIVATE_KEY; do
  echo "  $line" >> credentials.yml
done

bosh-cli build-manifest $MANIFEST_PATH -l credentials.yml > manifest/manifest.yml
