#!/usr/bin/env bash

set -e

cat > credentials.yml <<EOF
revok-github-access-token: $GITHUB_ACCESS_TOKEN

revok-mysql-username: $MYSQL_USERNAME
revok-mysql-password: $MYSQL_PASSWORD
revok-mysql-hostname: $MYSQL_HOSTNAME

revok-datadog-api-key: $DATADOG_API_KEY

revok-papertrail-address: $PAPERTRAIL_ADDRESS
EOF


echo "revok-github-private-key: |" >> credentials.yml
for line in $GITHUB_PRIVATE_KEY; do
  echo "  $line"
done

echo "revok-github-public-key: |" >> credentials.yml
for line in $GITHUB_PUBLIC_KEY; do
  echo "  $line"
done

bosh-cli build-manifest sec-red-deployments/gcp/revok/bosh.yml -l credentials.yml > manifest/manifest.yml
