#!/usr/bin/env bash

set -e

export GOPATH=$PWD/cred-alert
export PATH=$GOPATH/bin:$PATH

pushd ${GOPATH}/src/teamstr
  go run cmd/teamstr/main.go --token "${TOKEN}" --team "${TEAM_NAME}" --organization "${ORG_NAME}"
popd
