#!/usr/bin/env bash

set -e

export GOPATH=$PWD/cred-alert
export PATH=$GOPATH/bin:$PATH

service mysql start

pushd ${GOPATH}
  go install github.com/onsi/ginkgo/ginkgo

  ./scripts/test -race $@
popd
