#!/usr/bin/env bash

set -e

export GOPATH=$PWD/cred-alert
export PATH=$GOPATH/bin:$PATH

service mysql start

pushd ${GOPATH}/src/cred-alert
  go install github.com/onsi/ginkgo/ginkgo
  ginkgo -r -p -race "$@"
popd
