#!/usr/bin/env bash
set -eu -o pipefail

export GOPATH="${PWD}/go"
export PATH="${GOPATH}/bin:${PATH}"

cred_alert_root=$(cd "$(dirname "${BASH_SOURCE}")"; cd ../..; pwd)

pushd "${cred_alert_root}"
  scripts/test
popd
