---
platform: linux

inputs:
- name: cred-alert
  path: go/src/github.com/pivotal-cf/cred-alert

outputs:
- name: updated-repo

run:
  path: go/src/github.com/pivotal-cf/cred-alert/ci/scripts/update-dependencies
