// This file was generated by counterfeiter
package revokfakes

import (
	"cred-alert/db"
	"cred-alert/revok"
	"sync"

	git "github.com/libgit2/git2go"

	"code.cloudfoundry.org/lager"
)

type FakeScanner struct {
	ScanStub        func(lager.Logger, string, string, map[git.Oid]struct{}, string, string, string) error
	scanMutex       sync.RWMutex
	scanArgsForCall []struct {
		arg1 lager.Logger
		arg2 string
		arg3 string
		arg4 map[git.Oid]struct{}
		arg5 string
		arg6 string
		arg7 string
	}
	scanReturns struct {
		result1 error
	}
	ScanNoNotifyStub        func(lager.Logger, string, string, map[git.Oid]struct{}, string, string, string) ([]db.Credential, error)
	scanNoNotifyMutex       sync.RWMutex
	scanNoNotifyArgsForCall []struct {
		arg1 lager.Logger
		arg2 string
		arg3 string
		arg4 map[git.Oid]struct{}
		arg5 string
		arg6 string
		arg7 string
	}
	scanNoNotifyReturns struct {
		result1 []db.Credential
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeScanner) Scan(arg1 lager.Logger, arg2 string, arg3 string, arg4 map[git.Oid]struct{}, arg5 string, arg6 string, arg7 string) error {
	fake.scanMutex.Lock()
	fake.scanArgsForCall = append(fake.scanArgsForCall, struct {
		arg1 lager.Logger
		arg2 string
		arg3 string
		arg4 map[git.Oid]struct{}
		arg5 string
		arg6 string
		arg7 string
	}{arg1, arg2, arg3, arg4, arg5, arg6, arg7})
	fake.recordInvocation("Scan", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6, arg7})
	fake.scanMutex.Unlock()
	if fake.ScanStub != nil {
		return fake.ScanStub(arg1, arg2, arg3, arg4, arg5, arg6, arg7)
	} else {
		return fake.scanReturns.result1
	}
}

func (fake *FakeScanner) ScanCallCount() int {
	fake.scanMutex.RLock()
	defer fake.scanMutex.RUnlock()
	return len(fake.scanArgsForCall)
}

func (fake *FakeScanner) ScanArgsForCall(i int) (lager.Logger, string, string, map[git.Oid]struct{}, string, string, string) {
	fake.scanMutex.RLock()
	defer fake.scanMutex.RUnlock()
	return fake.scanArgsForCall[i].arg1, fake.scanArgsForCall[i].arg2, fake.scanArgsForCall[i].arg3, fake.scanArgsForCall[i].arg4, fake.scanArgsForCall[i].arg5, fake.scanArgsForCall[i].arg6, fake.scanArgsForCall[i].arg7
}

func (fake *FakeScanner) ScanReturns(result1 error) {
	fake.ScanStub = nil
	fake.scanReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeScanner) ScanNoNotify(arg1 lager.Logger, arg2 string, arg3 string, arg4 map[git.Oid]struct{}, arg5 string, arg6 string, arg7 string) ([]db.Credential, error) {
	fake.scanNoNotifyMutex.Lock()
	fake.scanNoNotifyArgsForCall = append(fake.scanNoNotifyArgsForCall, struct {
		arg1 lager.Logger
		arg2 string
		arg3 string
		arg4 map[git.Oid]struct{}
		arg5 string
		arg6 string
		arg7 string
	}{arg1, arg2, arg3, arg4, arg5, arg6, arg7})
	fake.recordInvocation("ScanNoNotify", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6, arg7})
	fake.scanNoNotifyMutex.Unlock()
	if fake.ScanNoNotifyStub != nil {
		return fake.ScanNoNotifyStub(arg1, arg2, arg3, arg4, arg5, arg6, arg7)
	} else {
		return fake.scanNoNotifyReturns.result1, fake.scanNoNotifyReturns.result2
	}
}

func (fake *FakeScanner) ScanNoNotifyCallCount() int {
	fake.scanNoNotifyMutex.RLock()
	defer fake.scanNoNotifyMutex.RUnlock()
	return len(fake.scanNoNotifyArgsForCall)
}

func (fake *FakeScanner) ScanNoNotifyArgsForCall(i int) (lager.Logger, string, string, map[git.Oid]struct{}, string, string, string) {
	fake.scanNoNotifyMutex.RLock()
	defer fake.scanNoNotifyMutex.RUnlock()
	return fake.scanNoNotifyArgsForCall[i].arg1, fake.scanNoNotifyArgsForCall[i].arg2, fake.scanNoNotifyArgsForCall[i].arg3, fake.scanNoNotifyArgsForCall[i].arg4, fake.scanNoNotifyArgsForCall[i].arg5, fake.scanNoNotifyArgsForCall[i].arg6, fake.scanNoNotifyArgsForCall[i].arg7
}

func (fake *FakeScanner) ScanNoNotifyReturns(result1 []db.Credential, result2 error) {
	fake.ScanNoNotifyStub = nil
	fake.scanNoNotifyReturns = struct {
		result1 []db.Credential
		result2 error
	}{result1, result2}
}

func (fake *FakeScanner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.scanMutex.RLock()
	defer fake.scanMutex.RUnlock()
	fake.scanNoNotifyMutex.RLock()
	defer fake.scanNoNotifyMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeScanner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ revok.Scanner = new(FakeScanner)
