// Code generated by counterfeiter. DO NOT EDIT.
package revokfakes

import (
	"cred-alert/db"
	"cred-alert/revok"
	"sync"

	"code.cloudfoundry.org/lager"
)

type FakeRescannerScanner struct {
	ScanStub        func(lager.Logger, string, string, map[string]struct{}, string, string, string) ([]db.Credential, error)
	scanMutex       sync.RWMutex
	scanArgsForCall []struct {
		arg1 lager.Logger
		arg2 string
		arg3 string
		arg4 map[string]struct{}
		arg5 string
		arg6 string
		arg7 string
	}
	scanReturns struct {
		result1 []db.Credential
		result2 error
	}
	scanReturnsOnCall map[int]struct {
		result1 []db.Credential
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeRescannerScanner) Scan(arg1 lager.Logger, arg2 string, arg3 string, arg4 map[string]struct{}, arg5 string, arg6 string, arg7 string) ([]db.Credential, error) {
	fake.scanMutex.Lock()
	ret, specificReturn := fake.scanReturnsOnCall[len(fake.scanArgsForCall)]
	fake.scanArgsForCall = append(fake.scanArgsForCall, struct {
		arg1 lager.Logger
		arg2 string
		arg3 string
		arg4 map[string]struct{}
		arg5 string
		arg6 string
		arg7 string
	}{arg1, arg2, arg3, arg4, arg5, arg6, arg7})
	fake.recordInvocation("Scan", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6, arg7})
	fake.scanMutex.Unlock()
	if fake.ScanStub != nil {
		return fake.ScanStub(arg1, arg2, arg3, arg4, arg5, arg6, arg7)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.scanReturns.result1, fake.scanReturns.result2
}

func (fake *FakeRescannerScanner) ScanCallCount() int {
	fake.scanMutex.RLock()
	defer fake.scanMutex.RUnlock()
	return len(fake.scanArgsForCall)
}

func (fake *FakeRescannerScanner) ScanArgsForCall(i int) (lager.Logger, string, string, map[string]struct{}, string, string, string) {
	fake.scanMutex.RLock()
	defer fake.scanMutex.RUnlock()
	return fake.scanArgsForCall[i].arg1, fake.scanArgsForCall[i].arg2, fake.scanArgsForCall[i].arg3, fake.scanArgsForCall[i].arg4, fake.scanArgsForCall[i].arg5, fake.scanArgsForCall[i].arg6, fake.scanArgsForCall[i].arg7
}

func (fake *FakeRescannerScanner) ScanReturns(result1 []db.Credential, result2 error) {
	fake.ScanStub = nil
	fake.scanReturns = struct {
		result1 []db.Credential
		result2 error
	}{result1, result2}
}

func (fake *FakeRescannerScanner) ScanReturnsOnCall(i int, result1 []db.Credential, result2 error) {
	fake.ScanStub = nil
	if fake.scanReturnsOnCall == nil {
		fake.scanReturnsOnCall = make(map[int]struct {
			result1 []db.Credential
			result2 error
		})
	}
	fake.scanReturnsOnCall[i] = struct {
		result1 []db.Credential
		result2 error
	}{result1, result2}
}

func (fake *FakeRescannerScanner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.scanMutex.RLock()
	defer fake.scanMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeRescannerScanner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ revok.RescannerScanner = new(FakeRescannerScanner)
