// This file was generated by counterfeiter
package revokfakes

import (
	"cred-alert/db"
	"cred-alert/revok"
	"sync"

	"code.cloudfoundry.org/lager"
)

type FakeChangeFetcher struct {
	FetchStub        func(lager.Logger, db.Repository) error
	fetchMutex       sync.RWMutex
	fetchArgsForCall []struct {
		arg1 lager.Logger
		arg2 db.Repository
	}
	fetchReturns struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeChangeFetcher) Fetch(arg1 lager.Logger, arg2 db.Repository) error {
	fake.fetchMutex.Lock()
	fake.fetchArgsForCall = append(fake.fetchArgsForCall, struct {
		arg1 lager.Logger
		arg2 db.Repository
	}{arg1, arg2})
	fake.recordInvocation("Fetch", []interface{}{arg1, arg2})
	fake.fetchMutex.Unlock()
	if fake.FetchStub != nil {
		return fake.FetchStub(arg1, arg2)
	} else {
		return fake.fetchReturns.result1
	}
}

func (fake *FakeChangeFetcher) FetchCallCount() int {
	fake.fetchMutex.RLock()
	defer fake.fetchMutex.RUnlock()
	return len(fake.fetchArgsForCall)
}

func (fake *FakeChangeFetcher) FetchArgsForCall(i int) (lager.Logger, db.Repository) {
	fake.fetchMutex.RLock()
	defer fake.fetchMutex.RUnlock()
	return fake.fetchArgsForCall[i].arg1, fake.fetchArgsForCall[i].arg2
}

func (fake *FakeChangeFetcher) FetchReturns(result1 error) {
	fake.FetchStub = nil
	fake.fetchReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeChangeFetcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.fetchMutex.RLock()
	defer fake.fetchMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeChangeFetcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ revok.ChangeFetcher = new(FakeChangeFetcher)
