#!/bin/bash

set -e
absolute_path() {
  (cd $1 && pwd)
}


scripts_path=./$(dirname $0)
CRED_ALERT_CI_TARGET=wings
CRED_ALERT_RELEASE_DIR=${CRED_ALERT_RELEASE_DIR:-$(absolute_path $scripts_path/..)}

if [ -n "${CRED_ALERT_CI_TARGET}" ]; then
  target="-t ${CRED_ALERT_CI_TARGET}"
else
  target="-t wings"
fi

fly ${target} execute -p -c $CRED_ALERT_RELEASE_DIR/ci/test.yml -i cred-alert=$PWD -- "$@"
