#!/usr/bin/env bash
set -eu -o pipefail

cred_alert_path=$(cd "$(dirname "${BASH_SOURCE}")"; cd ..; pwd)

cred_alert_image="pivotalcf/cred-alert-ci:latest"

docker pull "${cred_alert_image}"

docker run \
  -v "${cred_alert_path}":/go/src/github.com/pivotal-cf/cred-alert \
  -it "${cred_alert_image}"
