#!/bin/bash
# vim: set ft=sh

gosub list \
  -a cred-alert/cmd/cred-alert-cli \
  -t cred-alert/cmd/cred-alert-cli \
  -a cred-alert/cmd/cred-alert-ingestor \
  -a cred-alert/cmd/cred-alert-worker \
  -a teamstr/cmd/teamstr \
  -a github.com/onsi/ginkgo \
  -a github.com/onsi/gomega \
  -a github.com/golang/protobuf \
  -a github.com/jinzhu/gorm \
  -a github.com/mattn/go-sqlite3 \
  | xargs gosub sync
