#!/bin/bash
# vim: set ft=sh

gosub list \
  -a cred-alert/cmd/cred-alert-cli \
  -t cred-alert/cmd/cred-alert-cli \
  -a cred-alert/cmd/revok-worker \
  -a cred-alert/cmd/revok-ingestor \
  -a cred-alert/cmd/credential-count-publisher \
  -t rats \
  -a teamstr/cmd/teamstr \
  -a rolodex/cmd/rolodexd \
  | xargs gosub sync
