#!/bin/bash

set -e

set -o pipefail

pushd packages/cred-alert > /dev/null
  {
    cat spec | grep -v '# gosub'
    gosub list \
      -a cred-alert/cmd/revok-worker \
      -a cred-alert/cmd/revok-ingestor \
      -a cred-alert/cmd/revok-api \
      | \
      sed -e 's%\(.*\)%  - \1/*.{go,c} # gosub%g'
  } > spec.new

  mv spec.new spec
popd > /dev/null

pushd packages/rolodex > /dev/null
  {
    cat spec | grep -v '# gosub'
    gosub list \
      -a rolodex/cmd/rolodexd \
      | \
      sed -e 's%\(.*\)%  - \1/*.{go,c} # gosub%g'
  } > spec.new

  mv spec.new spec
popd > /dev/null
