#!/bin/bash

set -e

set -o pipefail

pushd packages/cred-alert
  {
    cat spec | grep -v '# gosub'
    gosub list -a cred-alert/cmd/cred-alert-worker-ng | \
      sed -e 's%\(.*\)%  - \1/*.{go,c} # gosub%g'
  } > spec.new

  mv spec.new spec
popd
