---
resources:
- name: golang
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/library/golang
    tag: latest

- name: github-release
  type: github-release
  source:
    user: pivotal-cf
    repository: cred-alert
    access_token: ((ci-credentials.sec-triage-ci-write))

- name: cred-alert-image
  type: docker-image
  source:
    repository: harbor-repo.vmware.com/davos/cred-alert-ci
    username: ((harbor-internal.username))
    password: ((harbor-internal.password))

- name: cred-alert-docker
  type: git
  source:
    uri: git@github.com:pivotal-cf/cred-alert.git
    branch: master
    private_key: ((ci-credentials.pcf-sec-triage-ci-github-key))
    paths:
    - ci/docker/Dockerfile

- name: cred-alert
  type: git
  source:
    uri: git@github.com:pivotal-cf/cred-alert.git
    branch: master
    private_key: ((ci-credentials.pcf-sec-triage-ci-github-key))
    ignore_paths:
    - ci/docker/Dockerfile

- name: cli-linux
  type: s3
  source:
    bucket: cred-alert
    access_key_id: ((ci-credentials.sec-red-ci-access-key-id))
    secret_access_key: ((ci-credentials.sec-red-ci-secret-access-key))
    versioned_file: cli/current-release/cred-alert-cli_linux

- name: cli-darwin
  type: s3
  source:
    bucket: cred-alert
    access_key_id: ((ci-credentials.sec-red-ci-access-key-id))
    secret_access_key: ((ci-credentials.sec-red-ci-secret-access-key))
    versioned_file: cli/current-release/cred-alert-cli_darwin

jobs:
- name: build-image
  serial: true
  plan:
  - in_parallel:
    - get: cred-alert-docker
      trigger: true
    - get: golang
      trigger: true
      params: {save: true}
  - put: cred-alert-image
    params:
      load_base: golang
      build: cred-alert-docker/ci/docker

- name: update-dependencies
  serial: true
  plan:
  - in_parallel:
    - get: cred-alert
    - get: cred-alert-image
  - task: update-dependencies
    image: cred-alert-image
    file: cred-alert/ci/tasks/update-dependencies.yml
  - task: test
    image: cred-alert-image
    file: cred-alert/ci/tasks/test.yml
    input_mapping:
      cred-alert: updated-repo
  - put: cred-alert
    params:
      repository: updated-repo
      rebase: true

- name: test
  plan:
  - in_parallel:
    - get: cred-alert-image
      trigger: true
    - get: cred-alert
      trigger: true
  - task: test
    image: cred-alert-image
    file: cred-alert/ci/tasks/test.yml

- name: ship-cli
  plan:
  - in_parallel:
    - get: cred-alert-image
      passed: [test]
    - get: cred-alert
      passed: [test]
      params:
        submodules: none
  - task: test
    image: cred-alert-image
    file: cred-alert/ci/tasks/test.yml
  - task: compile-release
    image: cred-alert-image
    file: cred-alert/ci/tasks/compile-release.yml
  - put: github-release
    params:
      name: release-params/tag-name
      tag: release-params/tag-name
      commitish: release-params/commit-sha
      globs:
      - "cred-alert-cli/cred-alert-cli_linux"
      - "cred-alert-cli/cred-alert-cli_darwin"
  - in_parallel:
    - put: cli-linux
      params:
        file: "cred-alert-cli/cred-alert-cli_linux"
        acl: public-read
    - put: cli-darwin
      params:
        file: "cred-alert-cli/cred-alert-cli_darwin"
        acl: public-read
