// Code generated by counterfeiter. DO NOT EDIT.
package searchfakes

import (
	"cred-alert/search"
	"sync"

	"code.cloudfoundry.org/lager"
)

type FakeBlobSearcher struct {
	ListBlobsStub        func(logger lager.Logger, owner string, name string) ([]search.BlobResult, error)
	listBlobsMutex       sync.RWMutex
	listBlobsArgsForCall []struct {
		logger lager.Logger
		owner  string
		name   string
	}
	listBlobsReturns struct {
		result1 []search.BlobResult
		result2 error
	}
	listBlobsReturnsOnCall map[int]struct {
		result1 []search.BlobResult
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBlobSearcher) ListBlobs(logger lager.Logger, owner string, name string) ([]search.BlobResult, error) {
	fake.listBlobsMutex.Lock()
	ret, specificReturn := fake.listBlobsReturnsOnCall[len(fake.listBlobsArgsForCall)]
	fake.listBlobsArgsForCall = append(fake.listBlobsArgsForCall, struct {
		logger lager.Logger
		owner  string
		name   string
	}{logger, owner, name})
	fake.recordInvocation("ListBlobs", []interface{}{logger, owner, name})
	fake.listBlobsMutex.Unlock()
	if fake.ListBlobsStub != nil {
		return fake.ListBlobsStub(logger, owner, name)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.listBlobsReturns.result1, fake.listBlobsReturns.result2
}

func (fake *FakeBlobSearcher) ListBlobsCallCount() int {
	fake.listBlobsMutex.RLock()
	defer fake.listBlobsMutex.RUnlock()
	return len(fake.listBlobsArgsForCall)
}

func (fake *FakeBlobSearcher) ListBlobsArgsForCall(i int) (lager.Logger, string, string) {
	fake.listBlobsMutex.RLock()
	defer fake.listBlobsMutex.RUnlock()
	return fake.listBlobsArgsForCall[i].logger, fake.listBlobsArgsForCall[i].owner, fake.listBlobsArgsForCall[i].name
}

func (fake *FakeBlobSearcher) ListBlobsReturns(result1 []search.BlobResult, result2 error) {
	fake.ListBlobsStub = nil
	fake.listBlobsReturns = struct {
		result1 []search.BlobResult
		result2 error
	}{result1, result2}
}

func (fake *FakeBlobSearcher) ListBlobsReturnsOnCall(i int, result1 []search.BlobResult, result2 error) {
	fake.ListBlobsStub = nil
	if fake.listBlobsReturnsOnCall == nil {
		fake.listBlobsReturnsOnCall = make(map[int]struct {
			result1 []search.BlobResult
			result2 error
		})
	}
	fake.listBlobsReturnsOnCall[i] = struct {
		result1 []search.BlobResult
		result2 error
	}{result1, result2}
}

func (fake *FakeBlobSearcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.listBlobsMutex.RLock()
	defer fake.listBlobsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBlobSearcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ search.BlobSearcher = new(FakeBlobSearcher)
